services:

  fe:
    build: fe/
    ports:
      - "80:80"
    depends_on:
      be:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s


  be:
    build: be/
    env_file:
      - be/.env
    environment:
      - ENV=prod
      - POSTGRES_HOST=db
      - DATABASE_URL=postgres://copit:abc@db/copit
      - REDIS_URL=redis://redis/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s

  db:
    image: postgres:alpine
    volumes:
      - ./be/postgres/:/docker-entrypoint-initdb.d
    env_file:
      - be/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
